### ISSUE TITLE
[DEMO-INSTANCES] pouvoir tuer une instance

### ISSUE THREAD

**Issue by chbu1983** [bewiwi/DemoInstance#5]
Je voudrais monter une nouvelle instance from scratch mais je peux pas car j'ai encore une instance active pendant 90 minutes et je ne peux en avoir qu'une à la fois.

J'aimerai pouvoir tuer mon instance en cours pour libérer mon slot.

**Comment by bewiwi** [comment]
Done sur master, waiting docker build
